from game.ngame import sbox

def substitute(c):
    return [sbox[c[ 0]], sbox[c[ 1]], sbox[c[ 2]], sbox[c[ 3]], sbox[c[ 4]], sbox[c[ 5]], sbox[c[ 6]], sbox[c[ 7]],
            sbox[c[ 8]], sbox[c[ 9]], sbox[c[10]], sbox[c[11]], sbox[c[12]], sbox[c[13]], sbox[c[14]], sbox[c[15]],
            sbox[c[16]], sbox[c[17]], sbox[c[18]], sbox[c[19]], sbox[c[20]], sbox[c[21]], sbox[c[22]], sbox[c[23]],
            sbox[c[24]], sbox[c[25]], sbox[c[26]], sbox[c[27]], sbox[c[28]], sbox[c[29]], sbox[c[30]], sbox[c[31]]]

def permute(inp):
    return [inp[ 0]^inp[ 7]^inp[10]^inp[12]^inp[13]^inp[15]^inp[18]^inp[19]^inp[21]^inp[22]^inp[25]^inp[28]^inp[29]^inp[30]^inp[31],
            inp[ 1]^inp[ 4]^inp[ 7]^inp[10]^inp[11]^inp[12]^inp[14]^inp[15]^inp[16]^inp[18]^inp[21]^inp[23]^inp[25]^inp[26]^inp[28],
            inp[ 2]^inp[ 5]^inp[ 8]^inp[11]^inp[13]^inp[15]^inp[16]^inp[17]^inp[19]^inp[20]^inp[22]^inp[26]^inp[27]^inp[28]^inp[29],
            inp[ 3]^inp[ 6]^inp[ 9]^inp[12]^inp[14]^inp[17]^inp[18]^inp[20]^inp[21]^inp[23]^inp[24]^inp[27]^inp[28]^inp[29]^inp[30],
            inp[ 3]^inp[ 4]^inp[ 8]^inp[ 9]^inp[11]^inp[14]^inp[17]^inp[18]^inp[22]^inp[23]^inp[24]^inp[25]^inp[26]^inp[27]^inp[29],
            inp[ 0]^inp[ 3]^inp[ 5]^inp[ 8]^inp[10]^inp[11]^inp[14]^inp[15]^inp[17]^inp[19]^inp[20]^inp[22]^inp[24]^inp[29]^inp[30],
            inp[ 1]^inp[ 6]^inp[ 9]^inp[11]^inp[12]^inp[15]^inp[16]^inp[18]^inp[20]^inp[21]^inp[23]^inp[24]^inp[25]^inp[30]^inp[31],
            inp[ 2]^inp[ 7]^inp[ 8]^inp[10]^inp[13]^inp[16]^inp[17]^inp[19]^inp[21]^inp[22]^inp[24]^inp[25]^inp[26]^inp[28]^inp[31],
            inp[ 2]^inp[ 4]^inp[ 5]^inp[ 7]^inp[ 8]^inp[15]^inp[17]^inp[20]^inp[21]^inp[22]^inp[23]^inp[26]^inp[27]^inp[29]^inp[30],
            inp[ 2]^inp[ 3]^inp[ 4]^inp[ 6]^inp[ 7]^inp[ 9]^inp[12]^inp[15]^inp[17]^inp[18]^inp[20]^inp[24]^inp[26]^inp[29]^inp[31],
            inp[ 0]^inp[ 3]^inp[ 5]^inp[ 7]^inp[10]^inp[13]^inp[18]^inp[19]^inp[20]^inp[21]^inp[24]^inp[25]^inp[27]^inp[28]^inp[30],
            inp[ 1]^inp[ 4]^inp[ 6]^inp[11]^inp[14]^inp[16]^inp[19]^inp[20]^inp[21]^inp[22]^inp[25]^inp[26]^inp[28]^inp[29]^inp[31],
            inp[ 0]^inp[ 1]^inp[ 3]^inp[ 6]^inp[11]^inp[12]^inp[16]^inp[17]^inp[18]^inp[19]^inp[21]^inp[25]^inp[26]^inp[30]^inp[31],
            inp[ 0]^inp[ 2]^inp[ 3]^inp[ 6]^inp[ 7]^inp[ 8]^inp[11]^inp[13]^inp[16]^inp[21]^inp[22]^inp[25]^inp[27]^inp[28]^inp[30],
            inp[ 1]^inp[ 3]^inp[ 4]^inp[ 7]^inp[ 9]^inp[14]^inp[16]^inp[17]^inp[22]^inp[23]^inp[24]^inp[26]^inp[28]^inp[29]^inp[31],
            inp[ 0]^inp[ 2]^inp[ 5]^inp[10]^inp[15]^inp[16]^inp[17]^inp[18]^inp[20]^inp[23]^inp[24]^inp[25]^inp[27]^inp[29]^inp[30],
            inp[ 2]^inp[ 3]^inp[ 5]^inp[ 6]^inp[ 9]^inp[12]^inp[13]^inp[14]^inp[15]^inp[16]^inp[23]^inp[26]^inp[28]^inp[29]^inp[31],
            inp[ 0]^inp[ 2]^inp[ 5]^inp[ 7]^inp[ 9]^inp[10]^inp[12]^inp[17]^inp[20]^inp[23]^inp[26]^inp[27]^inp[28]^inp[30]^inp[31],
            inp[ 0]^inp[ 1]^inp[ 3]^inp[ 4]^inp[ 6]^inp[10]^inp[11]^inp[12]^inp[13]^inp[18]^inp[21]^inp[24]^inp[27]^inp[29]^inp[31],
            inp[ 1]^inp[ 2]^inp[ 4]^inp[ 5]^inp[ 7]^inp[ 8]^inp[11]^inp[12]^inp[13]^inp[14]^inp[19]^inp[22]^inp[25]^inp[28]^inp[30],
            inp[ 1]^inp[ 2]^inp[ 6]^inp[ 7]^inp[ 8]^inp[ 9]^inp[10]^inp[11]^inp[13]^inp[19]^inp[20]^inp[24]^inp[25]^inp[27]^inp[30],
            inp[ 1]^inp[ 3]^inp[ 4]^inp[ 6]^inp[ 8]^inp[13]^inp[14]^inp[16]^inp[19]^inp[21]^inp[24]^inp[26]^inp[27]^inp[30]^inp[31],
            inp[ 0]^inp[ 2]^inp[ 4]^inp[ 5]^inp[ 7]^inp[ 8]^inp[ 9]^inp[14]^inp[15]^inp[17]^inp[22]^inp[25]^inp[27]^inp[28]^inp[31],
            inp[ 0]^inp[ 1]^inp[ 3]^inp[ 5]^inp[ 6]^inp[ 8]^inp[ 9]^inp[10]^inp[12]^inp[15]^inp[18]^inp[23]^inp[24]^inp[26]^inp[29],
            inp[ 1]^inp[ 4]^inp[ 5]^inp[ 6]^inp[ 7]^inp[10]^inp[11]^inp[13]^inp[14]^inp[18]^inp[20]^inp[21]^inp[23]^inp[24]^inp[31],
            inp[ 1]^inp[ 2]^inp[ 4]^inp[ 8]^inp[10]^inp[13]^inp[15]^inp[18]^inp[19]^inp[20]^inp[22]^inp[23]^inp[25]^inp[28]^inp[31],
            inp[ 2]^inp[ 3]^inp[ 4]^inp[ 5]^inp[ 8]^inp[ 9]^inp[11]^inp[12]^inp[14]^inp[16]^inp[19]^inp[21]^inp[23]^inp[26]^inp[29],
            inp[ 0]^inp[ 3]^inp[ 4]^inp[ 5]^inp[ 6]^inp[ 9]^inp[10]^inp[12]^inp[13]^inp[15]^inp[17]^inp[20]^inp[22]^inp[27]^inp[30],
            inp[ 0]^inp[ 1]^inp[ 2]^inp[ 3]^inp[ 5]^inp[ 9]^inp[10]^inp[14]^inp[15]^inp[16]^inp[17]^inp[19]^inp[22]^inp[27]^inp[28],
            inp[ 0]^inp[ 5]^inp[ 6]^inp[ 9]^inp[11]^inp[12]^inp[14]^inp[16]^inp[18]^inp[19]^inp[22]^inp[23]^inp[24]^inp[27]^inp[29],
            inp[ 0]^inp[ 1]^inp[ 6]^inp[ 7]^inp[ 8]^inp[10]^inp[12]^inp[13]^inp[15]^inp[17]^inp[19]^inp[20]^inp[23]^inp[25]^inp[30],
            inp[ 0]^inp[ 1]^inp[ 2]^inp[ 4]^inp[ 7]^inp[ 8]^inp[ 9]^inp[11]^inp[13]^inp[14]^inp[16]^inp[18]^inp[21]^inp[26]^inp[31]]

def mix(c):
    return [sbox[c[ 0]]^sbox[c[ 1]+256],
            sbox[c[ 2]]^sbox[c[ 3]+256],
            sbox[c[ 4]]^sbox[c[ 5]+256],
            sbox[c[ 6]]^sbox[c[ 7]+256],
            sbox[c[ 8]]^sbox[c[ 9]+256],
            sbox[c[10]]^sbox[c[11]+256],
            sbox[c[12]]^sbox[c[13]+256],
            sbox[c[14]]^sbox[c[15]+256],
            sbox[c[16]]^sbox[c[17]+256],
            sbox[c[18]]^sbox[c[19]+256],
            sbox[c[20]]^sbox[c[21]+256],
            sbox[c[22]]^sbox[c[23]+256],
            sbox[c[24]]^sbox[c[25]+256],
            sbox[c[26]]^sbox[c[27]+256],
            sbox[c[28]]^sbox[c[29]+256],
            sbox[c[30]]^sbox[c[31]+256]]

def forward(c):
    c = forward_sp_network(c)
    mixed = mix(c)

    return "".join(chr(letter) for letter in mixed)

def forward_sp_network(c):
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    s = substitute(c)
    c = permute(s)
    return c
